version: '3.8'

services:
  websocket-server:
    build:
      context: ./server
    restart: unless-stopped

  websocket-client:
    build:
      context: ./client
    depends_on:
     - websocket-server
    restart: unless-stopped